using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Olivas.Numeros.Models
{

    public class Numeros
    {
        public int ValorLetra { get; set; }
        public string Letra { get; set; }
    }
    public static class Tabela
    {
        public static List<KeyValuePair<string, int>> ListaValorLetras = new List<KeyValuePair<string, int>>()
        {
                 new KeyValuePair<string, int>("a", 1),
                 new KeyValuePair<string, int>("b", 2),
                 new KeyValuePair<string, int>("c", 3),
                 new KeyValuePair<string, int>("d", 4),
                 new KeyValuePair<string, int>("e", 5),
                 new KeyValuePair<string, int>("f", 8),
                 new KeyValuePair<string, int>("g", 3),
                 new KeyValuePair<string, int>("h", 5),
                 new KeyValuePair<string, int>("i", 1),
                 new KeyValuePair<string, int>("j", 1),
                 new KeyValuePair<string, int>("k", 2),
                 new KeyValuePair<string, int>("l", 3),
                 new KeyValuePair<string, int>("m", 4),
                 new KeyValuePair<string, int>("n", 5),
                 new KeyValuePair<string, int>("o", 7),
                 new KeyValuePair<string, int>("p", 8),
                 new KeyValuePair<string, int>("q", 1),
                 new KeyValuePair<string, int>("r", 2),
                 new KeyValuePair<string, int>("s", 3),
                 new KeyValuePair<string, int>("t", 4),
                 new KeyValuePair<string, int>("u", 6),
                 new KeyValuePair<string, int>("v", 6),
                 new KeyValuePair<string, int>("x", 5),
                 new KeyValuePair<string, int>("w", 6),
                 new KeyValuePair<string, int>("y", 1),
                 new KeyValuePair<string, int>("z", 7),
                 new KeyValuePair<string, int>("é", 7),
                 new KeyValuePair<string, int>("í", 3),
                 new KeyValuePair<string, int>("ó", 9),
                 new KeyValuePair<string, int>("á", 3)
        };

        public static List<KeyValuePair<int, string>> ListaExpressao = new List<KeyValuePair<int, string>>()
        {
                new KeyValuePair<int, string>(1,
                     "O número um corresponde ao líder, às pessoas influentes, pioneiras, inventivas e planejadoras – embora muitas vezes essas " +
                     "pessoas realizem seus projetos sem levar em conta os envolvidos. Tendem a dominar, consciente ou inconscientemente, todos os seus conhecidos. Em vista da sua tremenda ousadia, vive a sonhar com grandes empreendimentos, pioneiros, sempre à procura de novidades, visando o presente e o futuro. O seu êxito profissional, afetivo ou pessoal, depende exclusivamente do seu modo de pensar, falar e proceder, pois como é individualista, dificilmente aceita conselhos ou sugestões de quem quer que seja. Em virtude da sua personalidade de aspecto arrogante e ditatorial, encontrará, ao longo da vida inúmeras dificuldades de relacionamento, sejam elas de cunho afetivo, pessoal ou mesmo profissional, levando-o a fazer amigos e inimigos com grande facilidade. Trabalhos subalternos, sem movimentação (como contador, caixa de banco, etc.), o deprimem, e diríamos até, o deixam “estressado”, pouco à vontade e insatisfeito. Deve trabalhar por conta própria ou em cargos de chefia, pois como tem os ouvidos “sensíveis”, não gosta de receber ordens, principalmente quando essa ordem parte de alguém com estudo inferior. Possui emoções poderosas e habilidades para dar e receber amor. Logo, é importante encontrar uma forma de expressar os seus sentimentos em vez de buscar realização em interesses financeiros. Se ficar desanimado, pode cairnos dramas emocionais de outras pessoas, pois a sua sensibilidade precisa encontrar uma via de escape. A ordem e o método são, em geral, benefícios para você, embora um plano de vida definido seja um pré-requisito para fazer bom uso do seu tremendo potencial. ORIENTAÇÃO: Em vista de ter tendência a começar muitas coisas e não terminá-las, deve adquirir conhecimentos, prudência, ponderação e sabedoria, para poder desenvolver o seu imenso potencial de realização e levar a bom termo os seus objetivos. "),
                new KeyValuePair<int, string>(2,
                     "O dois, apesar de não ser ambicioso, consegue tudo que deseja, mas sempre pela persuasão, nunca pela força. No lado negativo de seu caráter, destaca-se a hesitação constante e a falta de iniciativa, tendo tendência para adiar decisões importantes por qualquer motivo, levando-o a situações delicadas, principalmente no âmbito profissional e afetivo. Normalmente usa de destreza e sabedoria, trabalhando mais nos “bastidores”, ou seja, na retaguarda, para levar alegria e amor a todos os seus conhecidos. É cooperativo, de certa maneira tímido, vulnerável e até passivo, porém sempre atento a todos os detalhes de seu ambiente. Nasceu para trabalhar em conjunto com outras pessoas, dificilmente se adaptando a o comando, seja de que nível for. É detalhista e prefere fazer uso das suas habilidades inatas lidando com pessoas e satisfazendo seu desejo de eterna harmonia. Parte do seu sucesso provém do fato de aplicar suas habilidades e saber transformar a teoria em prática. Além disso, o ser dois é muito trabalhador, sempre pensando no sucesso; é, também, de certa forma ambicioso e com grande poder de liderança. Atento aos detalhes, é inventivo e sabe como ninguém solucionar problemas, seja de que nível for. Como é uma pessoa leal, grande parte da sua segurança é construída com amor e amizade; bons relacionamentos são importantes para a sua realização. ORIENTAÇÃO: O dois era chamado pelos antigos de a “mãe dos números e do casamento”. Como a sua grande virtude é a compreensão dos processos do conhecimento oculto, deve sempre cultivar este dom, a fim de poder viver condignamente, sem esperar que alguém ou algo o faça movimentar-se."),
  
                new KeyValuePair<int, string>(3,
                     "O três é o número da mais alta sabedoria e valor, da harmonia e da ação, do amor perfeito, da ternura e da força d’alma. É tremendamente apaixonado pela família (mesmo que não aparente), gosta de receber e dar amor e sente-se muito feliz em poder contribuir para a felicidade alheia. É ambicioso e dificilmente desiste dos seus ideais, seus objetivos. É um ser criativo e normalmente tem muitos amigos divertidos, além de possuir uma elevada percepção de beleza, cor e forma. O aspecto leve e espirituoso da sua personalidade sugere que gosta de se divertir e de se comunicar, e esses predicados, quando num elemento culturalmente desenvolvido, leva-o à procura de respostas para as questões mais profundas da vida, o que, no final das contas, acaba levando-o a explorar áreas mais espirituais ou místicas. Detesta receber ordens e trabalhar em uma profissão ou posição inferior, pois como sabe ter poderes e qualidades superior- res, também sabe como tirar proveito de qualquer situação que o possa fazer feliz. ORIENTAÇÃO: A vontade de aprender e a aversão à rotina indicam que você pode passar por diversas experiências na sua busca por uma carreira que o desafie mentalmente. " +
                     "Com a maneira persuasiva com que usa as palavras, pode ser bem sucedido no mundo da comunicação, vendas, escrita, arte ou área editorial, sendo, é claro, o chefe ou trabalhando por conta própria, pois tem grande aversão a ser mandado. " ),

                new KeyValuePair<int, string>(4,
                    "O quatro é o número da perseverança e da imortalidade, da descoberta e da consumação, da firmeza e do propósito, da realização das esperanças, das regras, dos poderes e da vontade. O novo lhe assusta e sente-se mais à vontade lidando com atividades rotineiras e já consagradas pela experiência. Gosta de construir coisas, mesmo que aparentemente não tenham maior serventia, pois é dotado de grande habilidade manual. Não suporta pessoas hipócritas, desonestas, preguiçosas e com falta de visão do futuro, e estas deficiências o tornam deprimido e triste. Não gosta de discussões fúteis, sem motivo aparente. Jamais guarda rancor, ressentimentos ou ódio de qualquer espécie, esquecendo rapidamente qualquer ofensa ou constrangimento. Sendo um espírito superior, o seu amor ao próximo é, simultaneamente, glória e dever. Usualmente, pode cooperar e se sair bem em trabalhos de equipe; entretanto, como não gosta de receber ordens, é preferível trabalhar por conta própria. É muito importante ser original, criar as suas próprias ideias e tomar as próprias decisões. Precisa aprender a ser persuasivo e não vigoroso ou autoritário. ORIENTAÇÃO: Como gosta da sua liberdade, evite fazer julgamentos ou criticar demais as pessoas, pois elas podem ficar ressentidas com as suas decisões e, assim, não lhe prestarem bons serviços ou não colaborarem com seus projetos. "),
                new KeyValuePair<int, string>(5,
                    "O cinco é o número dos criativos, dos ousados, dos agitados e dos amantes da liberdade. A característica deste número o impele a viajar pelo mundo sempre em busca de saber, de novas experiências e também prazer. É um ser sociável, agradável e sempre bem vindo em festas e reuniões. Gosta de ocupações diferentes, aquelas que o permitem estar em contato com pessoas, com o público, e que o deixem agir e exprimir-se livremente. Detesta receber ordens, principalmente de pessoas com estudo ou capacidade inferior às suas. Também não gosta de trabalhos pesados, enfadonhos, cansativos, preferindo os intelectuais, ou aqueles que o colocam em destaque, como chefe de vendas, de marketing, de criação, ou qualquer outro que implique no desejo de viver e pesquisar. Possui grande capacidade para lidar com quaisquer tipos de pessoas, sejam elas ricas, influentes ou intelectuais. O cinco, às vezes, tem surtos extraordinários de energia e coragem que lhe permitem reagir rapidamente a situações e agarrar as oportunidades. Possui uma mente excelente e precisa, e é capaz de ter pensamentos profundos, além de uma inclinação a pensar de forma técnica e analítica. O seu espírito independente o estimula a ver as coisas de uma maneira original e a buscar a liberdade pessoal. Porém, deve evitar ser voluntarioso ou obstinado e se tornar negativo e pouco comunicativo. ORIENTAÇÃO: Como terá muitas experiências na vida, deve usar essas experiências e o seu temperamento corajoso para levar até o fim os seus projetos, pois é de certa forma dispersivo, não conseguindo terminar o que começa, tendo mais começo do que fins. "),
                new KeyValuePair<int, string>(6,"O seis é um número de certa maneira contraditório; é o número da confusão e junção, da união e sedução, do vício e da virtude, da incerteza no casamento, do amor, da atração dos sexos e da beleza. Significa todos os tipos de problemas e discórdias, mas também é capaz de purificação pelo conhecimento e de uma vida elevada. A família é a base de sustentação de toda a sua vida. Amar e ser amado; eis o desejo maior do número seis. E quando privado desse amor, sente-se completamente perdido, sem saber o que fazer e como agir. Aparentemente calmo, pode explodir quando o contradizem ou criticam, principalmente quando nasce nos dias 29, 30, 31 ou primeiro de cada mês. O seis quer ver todos saudáveis, alegres e repletos de sucesso e felicidade. É pródigo em favorecer os outros, nada esperando em retribuição, passando inúmeras vezes por “otário”, pois as pessoas que favorece dificilmente retribuem os favores recebidos. Apesar de suas qualidades expressivas e brilhantes, pode ter dificuldades em fazer escolhas e tomar decisões. Como tem diversos interesses que o levam a diferentes direções, é muito importante ter um senso de propósito. Sem isso, pode ficar dividido entre os seus ideais e o desejo de satisfação material. Um lado da sua natureza pode ter uma forte atração por dinheiro, luxo e um estilo de vida indolente, mas o outro tem um desejo inspirador que pode levá-lo a trabalhar duro para realizar seus ideais. Qualquer que seja a sua escolha, terá muitas oportunidades e a habilidade de driblar as situações difíceis, graças ao seu charme e persuasão. Excelente marido, esposa ou amante, entrega-se por inteiro aos seus amores ou amizades, exigindo a mesm dedicação por parte dos outros, o que nem sempre acontece, frustrando-o e desestabilizando-o emocionalmente por longos períodos. ORIENTAÇÃO: Para se elevar e conquistar fama e fortuna deve procurar profissões de interesse humanitário, sempre incentivado pelos que ama. Deve, também, concentrar sua energia e não se preocupar com o que outras pessoas dizem ou fazem. Aprenda a dizer “não” sem medo de ofender os outros. "),
                new KeyValuePair<int, string>(7,"O sete é perfeccionista, de certa maneira arredio, por vezes calado, demora a esquentar um relacionamento, interessado em filosofia, religiosidade, política e assuntos extrafísicos. De grande intuição e discernimento, raramente segue as ideias alheias e só faz o que acredita. É vibrante em seus propósitos, honesto, leal, amigo, profundo, elevado moralmente, não gostando de futilidades e ilegalidades, e as atividades ou atos que as contenham, o deprimem e o entristecem. Como é um ator natural, muitas vezes passa uma imagem de autoconfiança. Em geral é perspicaz e inteligente, com um forte sexto sentido, pode avaliar rapidamente as pessoas e situações. Isso faz com que tenha um desempenho melhor quando ocupa uma posição de liderança em vez de se desgastar em trabalhos físicos. Mesmo que seja generoso, tanto quanto à sua disponibilidade de tempo quanto de dinheiro, pode se tornar expansivo e indulgente em excesso. Felizmente, é aberto às críticas, o que lhe permite usar a auto-análise como uma ferramenta valiosa, com poder de influenciar os demais. Por vezes é incompreendido, considerado estranho, um ser solitário, incomum, diferente. ORIENTAÇÃO: Deve controlar a sua vida e estabelecer primeiro uma base sólida. Deve aproveitar o que a vida tem de melhor e evitar o comodismo. Deve trabalhar em prol da humanida- de, em serviços que beneficiem a coletividade e que de alguma maneira o satisfaçam intelectual e também espiritualmente. Precisa meditar e receber inspiraçãodo eu interior. "),
                new KeyValuePair<int, string>(8,"O oito é considerado o número da atração e da repulsão, da vida, de todos os tipos de lutas, da separação, ruptura, destruição, expectativas e ameaças. Também é conhecido como o “portão da eternidade”. Dificilmente c o n s e g u e expressar seus sentimentos, parecendo frio e evasivo; a realidade é outra: é muito carinhoso, meigo, amoroso, carente de afeição e com muito calor humano. Em virtude destas características (ser uma coisa e parecer outra), tem tendência ao materialismo, ao acúmulo de bens materiais e também uma certa ganância de querer possuir a maior quantidade de dinheiro e bens possíveis. É organizadíssimo e muito dedicado à profissão, sendo excelente para lidar com situações concretas que requerem discernimento e constância. É austero, prático, direto, seguro de si, por vezes generoso, mas também se pode tornar violento quando as coisas não correm como deseja. Como é dotado de alto senso de justiça, jamais deve fazer qualquer transação comercial fraudulenta, pois essa “falta” poderá lhe ser muito prejudicial ao longo da existência. Normalmente não perde tempo lutando pela fortuna, pois sabe com absoluta certeza que conseguirá atingir seus objetivos. Com excelente capacidade de avaliação, lida com o dinheiro e as questões materiais de forma instintiva. Pode ter golpes de sorte ocasionais, combinando o seu sexto sentido com informações inesperadas. Como pode passar por períodos de instabilidade financeira, precisa equacionar o problema de como viver bem sem ser extravagante. A sua autoridade natural o leva a ocupar posições de responsabilidade, nas quais pode usar a sua capacidade de organização. E será melhor se isso envolver algum tipo de atividade criativa. ORIENTAÇÃO: Como é progressista, dá grande importância ao dinheiro, ao status social e deseja constantemente expressar livremente os seus sentimentos, deve evitar situações monótonas ou excesso de rigidez. Terá mais chance de se realizer como alto executivo, comerciante ou trabalhando por conta própria. "),
                new KeyValuePair<int, string>(9,"O nove é misterioso, silencioso e liga-se ao plano astral. É o número da sabedoria, da virtude, da experiência, dos mistérios, da moralidade, do valor, da soberania, do amor humano, da obscuridade, da proteção e dos frutos do mérito. Enfim, é o número dos universalistas, dos generosos, dos seres humanos sensíveis aos sofrimentos alheios e vivem constantemente em busca da “verdade”, da compreensão, adaptando-se a trabalhos que visam o engrandecimento do ser humano, não medindo esforços e sacrifícios para fazer o que pensa ser certo, ou seja, amar, proteger e defender opróximo. O nove é um pensador nato e dispõe de grande capacidade de raciocínio, observação, criatividade e compreensão, levando-o a conhecer o âmago e as qualidades de coisas e fatos. Deve sempre ser impessoal, pois como é universalista, o materialismo pode-lhe causar sérios desapontamentos e aborrecimentos, principalmente com respeito a “amigos” e parentes que considera íntegros e incapazes de ações ilícitas, mas que na realidade são falsos. Tem excelente capacidade para ganhar dinheiro, e também para perdê-lo. Mas o mais extraordinário, é o fato de “nunca” lhe faltar dinheiro para as despesas do dia-a-dia. A fé interior é um importante fator para a sua autoconfiança e sem ela pode passar por fases de insegurança, reserva ou falta de auto-estima. Perspicaz e de mente aguçada, entende as coisas rapidamente e as utiliza em seu benefício. Embora às vezes possa se preocupar muito com questões materiais, é através do uso da sabedoria interior e compreensão espiritual que pode superar a perspectiva fria ou cética. Ousando ser espontâneo e justo ao mesmo tempo, mas sem perder a competitividade, pode desafiar a si mesmo e aos outros sem se sentir arrogante ou poderoso. Frequentemente atraído por indivíduos criativos, tem grande necessidade de amor e compreensão que se opõe à sua aparência forte e assertiva. ORIENTAÇÃO: Como nasceu para ser livre, não deve se apegar a nada nem a ninguém, e sim amar e trabalhar em prol de toda a humanidade, sem nada esperar em troca. Evite ser destrutivo ou vingativo. Tente perceber a necessidade das outras pessoas e evite ser autocentrado ou crítico; evite dominar os outros com as suas opiniões. A compaixão e o amor trazem as maiores recompensas. "),
                new KeyValuePair<int, string>(11,"O onze é o número do poder, da bravura, da energia, do sucesso em aventuras destemidas, da liberdade. Suas vibrações são lunares e seus possuidores são idealistas, intuitivos, sensíveis, místicos, imaginativos e pensadores inspirados. O ser onze dificilmente é bem sucedido como negociante, sentindo-se mais à vontade em profissões agitadas, como política, marketing, administração de grandes empresas ou grandes projetos esotéricos, sociais e ideológicos. Profundo conhecedor da mente humana, normalmente se destaca dos demais, pois sendo um “número mestre”, consegue vislumbrar em seus amigos e inimigos, defeitos e virtudes que em outros números seria impossível. Tem fé em seus ideais e dificilmente volta atrás em suas decisões. Procura sempre ser justo, leal, compreensivo e viver em harmonia com todos. A vibração especial deste número sugere que o idealismo, a inspiração e a inovação são altamente importantes para o seu possuidor. Uma combinação de humildade e confiança o desafia a trabalhar para alcançar a independência financeira e espiritual. Através da experiência, pode aprender a lidar com os dois lados da sua natureza e desenvolver uma atitude menos extremista, acreditando nos seus sentimentos. Em geral, o onze tem muita energia e gosta de vitalidade, mas deve evitar o excesso de ansiedade e a falta de sentido prático Se não seguir os dogmas esotéricos e estudos profundos do “hermetismo”, pode-se tornar indolente, indeciso e sujeito à vontade alheia, sendo sugado e feito de empregado por seres muito mais inferiores do que ele. Como é um ser superior, normalmente atrai inveja e conflito das pessoas ao seu redor, fazendo amizades e inimizades com grande facilidade e, assim, dificultando a conclusão dos seus objetivos. ORIENTAÇÃO: Como todos os grandes seres humanos, aqueles que se destacam dos demais, o onze também tem certas dificuldades de adaptação ao meio ambiente, ao convívio com seres de inferior categoria, que não o compreendem, não o apóiam e ain- da o criticam. Deve ir em frente nos seus ideais sem se preocupar com o que os outros pensam de si. "),
                new KeyValuePair<int, string>(22,"As pessoas cujos nomes correspondem a vinte e dois – o número supremo – possuem todas as qualidades boas dos outros números. Se desejar algo que em princípio pareça impossível, vá em frente, pois com certeza conseguirá atingir o seu objetivo, e até com certa facilidade, pois é habilidoso, idealista, organizado e tem grande potencial de realização. Tem, ainda, outras qualidades: integridade moral, honestidade nata, inspiração divina, disciplina técnica e social, constância nos objetivos e grande capacidade para levar até ao fim um projeto ou um objetivo. Não é muito fácil conviver com ele, pois sendo “superior”, normalmente não se adapta a situações preconcebidas e muito menos gosta de aceitar ordens de quem quer que seja, gostando de trabalhar sozinho ou então em cargos de chefia. A ambição pode levá-lo ao mundo dos negócios, no qual pode se sobressair graças à sua capacidade de organização e administra- ção. Isto sugere também que pode vir a ser bem- sucedido nas áreas industrial, bancária, imobiliária e de merchandising. A sua visão e sua imaginação ativa podem levá- lo a seguir carreiras no teatro, fotografia, cinema ou decoração de interiores. A sua habilidade natural para lidar com as pessoas pode ser canalizada para profissões que envolvam o trato com o público, como comunicação, educação, medicina, trabalho social ou advocacia. O seu discer nimento especial e compaixão podem levá-lo a trabalhar no mundo da cura, seja na medicina tradicional ou na alternativa. ORIENTAÇÃO: Pode-se tornar famoso, tanto nacional como internacionalmente, pois como tem grande capacidade de persuasão e destreza com as palavras, consegue convencer a todos com seus argumentos e ideias, que outras não devem ser se não as que visem o bem da humanidade.Todo e qualquer vício lhe é altamente prejudicial, principalmente o fumo. ")

        };

    }
}