// <auto-generated />
namespace Olivas.Numeros.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Linha_piramide : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Linha_piramide));
        
        string IMigrationMetadata.Id
        {
            get { return "201907270208544_Linha_piramide"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
