// <auto-generated />
namespace Olivas.Numeros.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Ciclo_Momento_Missao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ciclo_Momento_Missao));
        
        string IMigrationMetadata.Id
        {
            get { return "201907270346219_Ciclo_Momento_Missao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
